using System.Diagnostics.Metrics;

namespace EnglishFlashcardGenerator.Core.Telemetry;

public static class FlashcardMetrics
{
    public const string MeterName = "EnglishFlashcardGenerator";
    public static readonly Meter Meter = new(MeterName);

    public static readonly Histogram<int> TeacherIterations = Meter.CreateHistogram<int>(
        "flashcards.teacher.iterations",
        description: "Number of bounces/iterations between teacher and critic per group");

    public static readonly Histogram<int> PlannerGroups = Meter.CreateHistogram<int>(
        "flashcards.planner.groups",
        description: "Number of linguistic groups identified by the planner per day");

    public static readonly Counter<int> CardsGenerated = Meter.CreateCounter<int>(
        "flashcards.cards.generated",
        description: "Total number of cards generated by the teacher (gross)");

    public static readonly Counter<int> CardsKept = Meter.CreateCounter<int>(
        "flashcards.cards.kept",
        description: "Final number of cards kept after critic review (net)");

    public static readonly Counter<int> CriticFindings = Meter.CreateCounter<int>(
        "flashcards.critic.findings",
        description: "Total number of explicit findings/issues raised by the critic");

    public static readonly Counter<int> GroupVerdicts = Meter.CreateCounter<int>(
        "flashcards.group.verdict",
        description: "Final verdict of a group (Approved, NeedsRevision, Rejected)");

    public static readonly Counter<long> PromptTokens = Meter.CreateCounter<long>(
        "flashcards.tokens.prompt",
        description: "Total number of prompt (input) tokens used");

    public static readonly Counter<long> CompletionTokens = Meter.CreateCounter<long>(
        "flashcards.tokens.completion",
        description: "Total number of completion (output) tokens used");
}
